# Generated by Django 3.1.6 on 2021-05-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Project',
        ),
    ]
