# Generated by Django 3.1.6 on 2021-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210520_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urlType',
            field=models.TextField(default='URL'),
        ),
    ]
