# Generated by Django 3.1.6 on 2021-06-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_urltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
