# Generated by Django 3.1.6 on 2021-06-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='path',
            new_name='path_file',
        ),
    ]
