# Generated by Django 3.1.6 on 2021-06-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210605_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.FilePathField(default=''),
        ),
    ]
