# Generated by Django 3.1.6 on 2021-06-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210606_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='path',
            new_name='file',
        ),
    ]
